// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAwSdXiIU3MxrpXi_UWoXEH3l_yvsyb9U',
    appId: '1:898179680592:web:cdd4def9ccf7c1f9184455',
    messagingSenderId: '898179680592',
    projectId: 'rehnaa-cd479',
    authDomain: 'rehnaa-cd479.firebaseapp.com',
    storageBucket: 'rehnaa-cd479.appspot.com',
    measurementId: 'G-K76488VPFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LmgHJ7dar5aKFIX41TxIhz1G0u7XocU',
    appId: '1:898179680592:android:5c4b221c7a150cf5184455',
    messagingSenderId: '898179680592',
    projectId: 'rehnaa-cd479',
    storageBucket: 'rehnaa-cd479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxamDVzHV0-67IRhMOrHKuBvhZSsmLmM',
    appId: '1:898179680592:ios:bea84a463eadde40184455',
    messagingSenderId: '898179680592',
    projectId: 'rehnaa-cd479',
    storageBucket: 'rehnaa-cd479.appspot.com',
    iosBundleId: 'com.example.rehnaa',
  );
}
